services:
  openwhisk:
    image: openwhisk/standalone:8f8a4aa
    container_name: openwhisk
    ports:
      - "3233:3233"
      - "3232:3232"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log
    restart: always
    network_mode: bridge
  cron:
    build: .
    container_name: my-cron
    network_mode: bridge
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rse_user
      POSTGRES_PASSWORD: rse_password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  postgres_data:
